import { calculateWindowBOM } from './bom-calculator';
import { Customer, InventoryItem, Project, WindowDesign } from './types';

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'CUST-01',
    name: 'Ramesh Kumar',
    phone: '+91 98490 23114',
    email: 'ramesh.kumar@gmail.com',
    address: 'Banjara Hills',
    city: 'Hyderabad',
  },
  {
    id: 'CUST-02',
    name: 'Suresh Reddy',
    phone: '+91 97033 11849',
    email: 'suresh.reddy@gmail.com',
    address: 'Jubilee Hills',
    city: 'Hyderabad',
  },
  {
    id: 'CUST-03',
    name: 'Anand Verma',
    phone: '+91 94401 55220',
    email: '',
    address: 'Whitefield',
    city: 'Bengaluru',
  },
  {
    id: 'CUST-04',
    name: 'Pooja Shenoy',
    phone: '+91 99802 87341',
    email: 'pooja.shenoy@gmail.com',
    address: 'Gachibowli',
    city: 'Hyderabad',
  },
  {
    id: 'CUST-05',
    name: 'Harish Bose',
    phone: '+91 98112 40992',
    email: 'harish.bose@gmail.com',
    address: 'Madhapur',
    city: 'Hyderabad',
  },
  {
    id: 'CUST-06',
    name: 'Vikram Reddy',
    phone: '+91 96521 88390',
    email: '',
    address: 'Financial District',
    city: 'Hyderabad',
  },
  {
    id: 'CUST-07',
    name: 'Deepak Chawla',
    phone: '+91 98850 49120',
    email: '',
    address: 'Kondapur',
    city: 'Hyderabad',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'INV-01',
    sku: 'VEK-CAS-60',
    name: 'VEKA 60mm Casement Outer Frame',
    specSubtitle: 'Multi-Chamber uPVC Profile (White RAL 9016)',
    seriesClassification: 'Casement Series (60mm)',
    seriesCategory: 'casement',
    brand: 'VEKA',
    brandName: 'VEKA Systems India',
    category: 'Profile',
    unit: 'm',
    stockQty: 1240,
    reservedQty: 240,
    availableQty: 1000,
    currentStock: 1240,
    minStock: 400,
    status: 'In Stock',
    secondaryStockDetail: '206.6 Bars (6.0m each)',
    reorderPoint: 400,
    unitPrice: 245,
    binLocation: 'Rack A-04 (Yard 1)',
    rackLocation: 'Rack A-04 (Yard 1)',
    iconType: 'profile',
  },
  {
    id: 'INV-02',
    sku: 'STL-15-BOX',
    name: 'Galvanized Steel Reinforcement 1.5mm Box',
    specSubtitle: 'Zinc-Coated Cold Rolled Core Profile',
    seriesClassification: 'Casement Steel Core',
    seriesCategory: 'glass_steel',
    brand: 'Tata Steel',
    brandName: 'Tata Steel Tubes Division',
    category: 'Steel',
    unit: 'm',
    stockQty: 480,
    reservedQty: 120,
    availableQty: 360,
    currentStock: 480,
    minStock: 250,
    status: 'In Stock',
    secondaryStockDetail: '80.0 Bars (6.0m each)',
    reorderPoint: 250,
    unitPrice: 85,
    binLocation: 'Steel Rack S-01',
    rackLocation: 'Steel Rack S-01',
    iconType: 'steel',
  },
  {
    id: 'INV-03',
    sku: 'KOM-SLD-88',
    name: 'Kommerling 88mm Sliding Sash Profile',
    specSubtitle: 'Anthracite Grey Renolit Foil Wrapped (5.8m)',
    seriesClassification: 'Sliding Series (88mm)',
    seriesCategory: 'sliding',
    brand: 'KOMMERLING',
    brandName: 'Kommerling Profiline',
    category: 'Profile',
    unit: 'm',
    stockQty: 120,
    reservedQty: 80,
    availableQty: 40,
    currentStock: 120,
    minStock: 200,
    status: 'Low Stock',
    secondaryStockDetail: '20.0 Bars (Low Stock Reorder)',
    reorderPoint: 200,
    unitPrice: 340,
    binLocation: 'Rack B-03',
    rackLocation: 'Rack B-03 (Yard 2)',
    iconType: 'sliding',
  },
  {
    id: 'INV-04',
    sku: 'GL-REH-24',
    name: 'Rehau Soundproof Glass Panel (DGU 24mm)',
    specSubtitle: 'Dual Glazed Acoustic Insulated Unit (5-14-5)',
    seriesClassification: 'Acoustic Glazing Series',
    seriesCategory: 'glass_steel',
    brand: 'REHAU',
    brandName: 'Rehau Acoustic Glazing',
    category: 'Glass',
    unit: 'sq.m',
    stockQty: 340,
    reservedQty: 60,
    availableQty: 280,
    currentStock: 340,
    minStock: 80,
    status: 'In Stock',
    secondaryStockDetail: '85 Pre-assembled Panes',
    reorderPoint: 80,
    unitPrice: 1150,
    binLocation: 'Glass Bay 02',
    rackLocation: 'Glass A-Frame Bay 02',
    iconType: 'glass',
  },
  {
    id: 'INV-05',
    sku: 'HDW-LK-09',
    name: 'Prominance Multi-Point Locking Handle Set',
    specSubtitle: 'Zinc Alloy Espagnolette Gearbox with Roller Cams',
    seriesClassification: 'Hardware & Fittings',
    seriesCategory: 'hardware',
    brand: 'Roto / Prominance',
    brandName: 'Prominance Hardware',
    category: 'Hardware',
    unit: 'pcs',
    stockQty: 28,
    reservedQty: 12,
    availableQty: 16,
    currentStock: 28,
    minStock: 50,
    status: 'Low Stock',
    secondaryStockDetail: '1.4 Cartons (20 pcs/box)',
    reorderPoint: 50,
    unitPrice: 420,
    binLocation: 'Bin H-14',
    rackLocation: 'Hardware Bin H-14',
    iconType: 'hardware',
  },
  {
    id: 'INV-06',
    sku: 'ALU-TT-70',
    name: 'Aluplast 70mm Tilt & Turn Frame Profile',
    specSubtitle: 'Golden Oak Woodgrain Foil (6.5m Bar)',
    seriesClassification: 'Tilt & Turn Series (70mm)',
    seriesCategory: 'tilt_turn',
    brand: 'Aluplast',
    brandName: 'Aluplast Profile Systems',
    category: 'Profile',
    unit: 'm',
    stockQty: 860,
    reservedQty: 150,
    availableQty: 710,
    currentStock: 860,
    minStock: 200,
    status: 'In Stock',
    secondaryStockDetail: '143.3 Bars (6.5m each)',
    reorderPoint: 200,
    unitPrice: 310,
    binLocation: 'Rack C-05',
    rackLocation: 'Rack C-05 (Yard 1)',
    iconType: 'profile',
  },
  {
    id: 'INV-07',
    sku: 'GL-SG-06',
    name: 'Saint-Gobain 6mm Toughened Glass Sheet',
    specSubtitle: 'Clear Tempered Grade A (10ft x 7ft Jumbo)',
    seriesClassification: 'Glass Sheets & Steel',
    seriesCategory: 'glass_steel',
    brand: 'Saint-Gobain',
    brandName: 'Saint-Gobain Glass India',
    category: 'Glass',
    unit: 'sq.m',
    stockQty: 18,
    reservedQty: 10,
    availableQty: 8,
    currentStock: 18,
    minStock: 40,
    status: 'Low Stock',
    secondaryStockDetail: '9 Sheets Remaining in Crate',
    reorderPoint: 40,
    unitPrice: 850,
    binLocation: 'Glass A-Frame 01',
    rackLocation: 'Glass A-Frame 01',
    iconType: 'glass',
  },
  {
    id: 'INV-08',
    sku: 'GSK-EPDM-01',
    name: 'EPDM Weathersealing Gasket Roll',
    specSubtitle: 'Double-Lip Co-extruded Vulcanized Rubber',
    seriesClassification: 'Hardware & Fittings',
    seriesCategory: 'hardware',
    brand: 'Generic',
    brandName: 'SecuSeal German Standard',
    category: 'Gasket',
    unit: 'm',
    stockQty: 1720,
    reservedQty: 320,
    availableQty: 1400,
    currentStock: 1720,
    minStock: 400,
    status: 'In Stock',
    secondaryStockDetail: '17.2 Rolls (100m each)',
    reorderPoint: 400,
    unitPrice: 18,
    binLocation: 'Bin G-04',
    rackLocation: 'Hardware Bin G-04',
    iconType: 'gasket',
  },
];

// Helper to create pre-designed sample windows
const w01BOM = calculateWindowBOM({
  id: 'W01',
  type: 'sliding_2track',
  width: 1200,
  height: 1500,
  profileBrand: 'VEKA',
  tracks: 2,
  sashes: 2,
  glassType: 'clear_5mm',
  meshType: 'none',
  hardware: {
    handleType: 'popup_flush',
    lockingPoints: 2,
    rollers: 'nylon_tandem',
  },
});

const w02BOM = calculateWindowBOM({
  id: 'W02',
  type: 'casement_single',
  width: 1000,
  height: 1200,
  profileBrand: 'VEKA',
  tracks: 1,
  sashes: 1,
  glassType: 'toughened_6mm',
  meshType: 'none',
  hardware: {
    handleType: 'friction_stay',
    lockingPoints: 2,
    rollers: 'standard',
  },
});

export const INITIAL_WINDOWS_PRJ1042: WindowDesign[] = [
  {
    id: 'W01',
    projectId: 'PRJ-1042',
    name: '2 Track Sliding',
    type: 'sliding_2track',
    profileBrand: 'VEKA',
    profileSeries: 'VEKA 84BS',
    width: 1200,
    height: 1500,
    tracks: 2,
    sashes: 2,
    mullions: 0,
    transoms: 0,
    openingDirection: 'sliding_left',
    glassType: 'clear_5mm',
    meshType: 'none',
    profileColor: 'pure_white',
    hardware: {
      handleType: 'popup_flush',
      lockingPoints: 2,
      rollers: 'nylon_tandem',
    },
    quantity: 1,
    unitPrice: 14500,
    status: 'DESIGNED',
    calculatedBOM: w01BOM,
    createdAt: '2026-09-02T10:00:00.000Z',
    updatedAt: '2026-09-02T10:00:00.000Z',
  },
  {
    id: 'W02',
    projectId: 'PRJ-1042',
    name: 'Casement',
    type: 'casement_single',
    profileBrand: 'VEKA',
    profileSeries: 'VEKA 84BS',
    width: 1000,
    height: 1200,
    tracks: 1,
    sashes: 1,
    mullions: 0,
    transoms: 0,
    openingDirection: 'casement_left',
    glassType: 'toughened_6mm',
    meshType: 'none',
    profileColor: 'pure_white',
    hardware: {
      handleType: 'friction_stay',
      lockingPoints: 2,
      rollers: 'standard',
    },
    quantity: 1,
    unitPrice: 16800,
    status: 'DESIGNED',
    calculatedBOM: w02BOM,
    createdAt: '2026-09-02T11:15:00.000Z',
    updatedAt: '2026-09-02T11:15:00.000Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'PRJ-1042',
    name: 'Ramesh Residence',
    customerId: 'CUST-01',
    customer: INITIAL_CUSTOMERS[0],
    siteAddress: 'Banjara Hills, Hyderabad',
    location: 'Banjara Hills',
    specSummary: '8 Windows (VEKA Sliding)',
    projectType: 'Residential',
    currentStage: 'quotation',
    status: 'Quotation Sent',
    dealStage: 'Quotation Sent',
    dealOwner: { name: 'Chakri S.', avatar: 'CS', color: 'bg-[#0A2E8A]' },
    lastActivity: {
      type: 'mail',
      text: 'Quote sent 2d ago',
    },
    estimatedValue: 240000,
    windows: INITIAL_WINDOWS_PRJ1042,
    quotation: {
      id: 'QT-1024',
      projectId: 'PRJ-1042',
      version: 1,
      revisions: [
        {
          version: 1,
          date: '2026-09-03',
          grandTotal: 240000,
          notes: 'Initial quotation with 8 Windows specification',
          createdBy: 'Chakri',
        },
      ],
      status: 'Sent',
      profileCost: 88500,
      glassCost: 45200,
      steelCost: 18400,
      hardwareCost: 26800,
      fabricationLaborCost: 22000,
      installationCost: 15000,
      transportationCost: 6000,
      subtotal: 221900,
      discountPercent: 5,
      discountAmount: 11095,
      gstPercent: 18,
      gstAmount: 37945,
      grandTotal: 240000,
      advancePercentage: 50,
      advanceRequired: 120000,
      notes: 'Includes Saint-Gobain 5mm/6mm glass and multi-point locking mechanisms. 10 years profile warranty.',
      terms: [
        '50% advance along with confirmed order & site measurement clearance.',
        '40% before dispatch of fabrication materials from factory.',
        '10% upon complete installation and handover.',
        'Lead time 10-14 working days from receipt of advance.',
      ],
      createdAt: '2026-09-03T09:00:00.000Z',
      validUntil: '2026-09-24T00:00:00.000Z',
    },
    payments: [],
    productionOrder: null,
    designLocked: false,
    nextAction: 'Follow Up',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-05T08:00:00.000Z',
  },
  {
    id: 'PRJ-1041',
    name: 'Suresh Villa',
    customerId: 'CUST-02',
    customer: INITIAL_CUSTOMERS[1],
    siteAddress: 'Jubilee Hills, Hyderabad',
    location: 'Jubilee Hills',
    specSummary: '12 Windows (Kommerling)',
    projectType: 'Villa',
    currentStage: 'quotation',
    status: 'Quotation Sent',
    dealStage: 'Advance Pending',
    dealOwner: { name: 'Ravi K.', avatar: 'RK', color: 'bg-slate-700' },
    lastActivity: {
      type: 'phone',
      text: 'Followed up yesterday',
    },
    estimatedValue: 380000,
    windows: INITIAL_WINDOWS_PRJ1042,
    quotation: {
      id: 'QT-1023',
      projectId: 'PRJ-1041',
      version: 1,
      revisions: [],
      status: 'Sent',
      profileCost: 145000,
      glassCost: 82000,
      steelCost: 32000,
      hardwareCost: 44000,
      fabricationLaborCost: 34000,
      installationCost: 22000,
      transportationCost: 9000,
      subtotal: 368000,
      discountPercent: 5,
      discountAmount: 18400,
      gstPercent: 18,
      gstAmount: 62928,
      grandTotal: 380000,
      advancePercentage: 50,
      advanceRequired: 190000,
      notes: '12 Luxury French & 3-Track Sliding Windows with Double Glazing (DGU).',
      terms: ['50% advance payment required to commence manufacturing.'],
      createdAt: '2026-09-02T14:30:00.000Z',
      validUntil: '2026-09-20T00:00:00.000Z',
    },
    payments: [],
    productionOrder: null,
    designLocked: false,
    nextAction: 'Follow Up',
    createdAt: '2026-08-28T11:00:00.000Z',
    updatedAt: '2026-09-02T14:30:00.000Z',
  },
  {
    id: 'PRJ-1040',
    name: 'Anand Heights',
    customerId: 'CUST-03',
    customer: INITIAL_CUSTOMERS[2],
    siteAddress: 'Whitefield, Bengaluru',
    location: 'Whitefield',
    specSummary: '4 Windows (Rehau Casement)',
    projectType: 'Residential',
    currentStage: 'design',
    status: 'Designing',
    dealStage: 'Site Survey',
    dealOwner: { name: 'Chakri S.', avatar: 'CS', color: 'bg-[#0A2E8A]' },
    lastActivity: {
      type: 'calendar',
      text: 'Scheduled tomorrow',
    },
    estimatedValue: 145000,
    windows: [
      {
        id: 'W01',
        projectId: 'PRJ-1040',
        name: 'Casement with Top Light',
        type: 'casement_single',
        profileBrand: 'VEKA',
        profileSeries: 'VEKA 70',
        width: 1200,
        height: 1500,
        tracks: 1,
        sashes: 1,
        mullions: 0,
        transoms: 1,
        openingDirection: 'casement_left',
        glassType: 'toughened_6mm',
        meshType: 'none',
        profileColor: 'pure_white',
        hardware: {
          handleType: 'friction_stay',
          lockingPoints: 2,
          rollers: 'standard',
        },
        quantity: 1,
        unitPrice: 15200,
        status: 'DESIGNED',
        calculatedBOM: w02BOM,
        createdAt: '2026-09-04T16:00:00.000Z',
        updatedAt: '2026-09-04T16:00:00.000Z',
      },
      {
        id: 'W02',
        projectId: 'PRJ-1040',
        name: 'Acoustic DGU Casement',
        type: 'casement_double',
        profileBrand: 'VEKA',
        profileSeries: 'VEKA 82',
        width: 1500,
        height: 1200,
        tracks: 1,
        sashes: 2,
        mullions: 1,
        transoms: 0,
        openingDirection: 'casement_left',
        glassType: 'dgu_5_12_5',
        meshType: 'none',
        profileColor: 'anthracite_grey',
        hardware: {
          handleType: 'friction_stay',
          lockingPoints: 3,
          rollers: 'standard',
        },
        quantity: 1,
        unitPrice: 22400,
        status: 'DESIGNED',
        calculatedBOM: w02BOM,
        createdAt: '2026-09-04T16:30:00.000Z',
        updatedAt: '2026-09-04T16:30:00.000Z',
      },
    ],
    quotation: null,
    payments: [],
    productionOrder: null,
    designLocked: false,
    nextAction: 'Send Quotation',
    createdAt: '2026-09-04T16:00:00.000Z',
    updatedAt: '2026-09-04T16:00:00.000Z',
  },
  {
    id: 'PRJ-1039',
    name: 'Oakridge Tower 2B',
    customerId: 'CUST-04',
    customer: INITIAL_CUSTOMERS[3],
    siteAddress: 'Gachibowli, Hyderabad',
    location: 'Gachibowli',
    specSummary: '6 Windows (VEKA Special Arch)',
    projectType: 'Builder / Apartment',
    currentStage: 'design',
    status: 'Designing',
    dealStage: 'Design & CAD',
    dealOwner: { name: 'Pooja V.', avatar: 'PV', color: 'bg-amber-700' },
    lastActivity: {
      type: 'cad',
      text: 'CAD drafting ongoing',
    },
    estimatedValue: 205000,
    windows: [
      {
        id: 'W01',
        projectId: 'PRJ-1039',
        name: '3-Track Sliding with Bug Mesh',
        type: 'sliding_3track',
        profileBrand: 'VEKA',
        profileSeries: 'VEKA Softline',
        width: 2400,
        height: 2100,
        tracks: 3,
        sashes: 3,
        mullions: 0,
        transoms: 0,
        openingDirection: 'sliding_left',
        glassType: 'clear_5mm',
        meshType: 'ss304_mesh',
        profileColor: 'pure_white',
        hardware: {
          handleType: 'popup_flush',
          lockingPoints: 3,
          rollers: 'brass_heavy',
        },
        quantity: 1,
        unitPrice: 28500,
        status: 'DESIGNED',
        calculatedBOM: w01BOM,
        createdAt: '2026-09-05T12:00:00.000Z',
        updatedAt: '2026-09-05T12:00:00.000Z',
      },
    ],
    quotation: null,
    payments: [],
    productionOrder: null,
    designLocked: false,
    nextAction: 'Send Quotation',
    createdAt: '2026-09-05T12:00:00.000Z',
    updatedAt: '2026-09-05T12:00:00.000Z',
  },
  {
    id: 'PRJ-1038',
    name: 'Skyline Penthouse',
    customerId: 'CUST-05',
    customer: INITIAL_CUSTOMERS[4],
    siteAddress: 'Madhapur, Hyderabad',
    location: 'Madhapur',
    specSummary: '14 Windows (Kommerling Charcoal)',
    projectType: 'Villa',
    currentStage: 'quotation',
    status: 'Quotation Sent',
    dealStage: 'Quotation Sent',
    dealOwner: { name: 'Ravi K.', avatar: 'RK', color: 'bg-slate-700' },
    lastActivity: {
      type: 'eye',
      text: 'Viewed quote 3h ago',
    },
    estimatedValue: 420000,
    windows: INITIAL_WINDOWS_PRJ1042,
    quotation: {
      id: 'QT-1021',
      projectId: 'PRJ-1038',
      version: 1,
      revisions: [],
      status: 'Sent',
      profileCost: 160000,
      glassCost: 90000,
      steelCost: 35000,
      hardwareCost: 45000,
      fabricationLaborCost: 40000,
      installationCost: 30000,
      transportationCost: 20000,
      subtotal: 420000,
      discountPercent: 0,
      discountAmount: 0,
      gstPercent: 18,
      gstAmount: 75600,
      grandTotal: 420000,
      advancePercentage: 50,
      advanceRequired: 210000,
      notes: '14 Custom Charcoal laminated windows with triple seal EPDM.',
      terms: ['50% advance to initiate extrusion ordering.'],
      createdAt: '2026-09-06T10:00:00.000Z',
      validUntil: '2026-09-25T00:00:00.000Z',
    },
    payments: [],
    productionOrder: null,
    designLocked: false,
    nextAction: 'Follow Up',
    createdAt: '2026-09-03T10:00:00.000Z',
    updatedAt: '2026-09-06T10:00:00.000Z',
  },
  {
    id: 'PRJ-1037',
    name: 'Vikram Villa',
    customerId: 'CUST-06',
    customer: INITIAL_CUSTOMERS[5],
    siteAddress: 'Financial District, Hyderabad',
    location: 'Financial District',
    specSummary: '6 Windows (VEKA Sliding)',
    projectType: 'Villa',
    currentStage: 'production',
    status: 'In Production',
    dealStage: 'Won - In Production',
    dealOwner: { name: 'Chakri S.', avatar: 'CS', color: 'bg-[#0A2E8A]' },
    lastActivity: {
      type: 'payment',
      text: 'Advance received ₹1.05L',
    },
    estimatedValue: 210000,
    windows: INITIAL_WINDOWS_PRJ1042,
    quotation: {
      id: 'QT-1020',
      projectId: 'PRJ-1037',
      version: 1,
      revisions: [],
      status: 'Approved',
      profileCost: 80000,
      glassCost: 40000,
      steelCost: 20000,
      hardwareCost: 25000,
      fabricationLaborCost: 20000,
      installationCost: 15000,
      transportationCost: 10000,
      subtotal: 210000,
      discountPercent: 0,
      discountAmount: 0,
      gstPercent: 18,
      gstAmount: 37800,
      grandTotal: 210000,
      advancePercentage: 50,
      advanceRequired: 105000,
      notes: 'Approved and in factory fabrication.',
      terms: ['50% advance received.'],
      createdAt: '2026-08-25T09:00:00.000Z',
      validUntil: '2026-09-15T00:00:00.000Z',
    },
    payments: [
      {
        id: 'PAY-02',
        projectId: 'PRJ-1037',
        receiptNumber: 'REC-2026-079',
        amount: 105000,
        paymentType: 'Advance (50%)',
        method: 'Bank NEFT/RTGS',
        reference: 'ICICI-NEFT-88390',
        date: '2026-09-01',
        notes: '50% advance confirmed.',
      },
    ],
    productionOrder: {
      id: 'PO-8819',
      projectId: 'PRJ-1037',
      status: 'Cutting',
      cuttingProgress: 75,
      assemblyProgress: 30,
      qcChecklist: {
        dimensionsVerified: true,
        weldsCleaned: true,
        reinforcementChecked: true,
        glassGasketsTight: false,
        hardwareSmoothAction: false,
        protectiveFilmIntact: true,
      },
      qcStatus: 'Pending',
      qcNotes: 'Profile cutting completed, sash assembly in progress.',
      allocatedWorker: 'Mahesh (Senior Fabricator)',
      createdAt: '2026-09-02T08:00:00.000Z',
    },
    designLocked: true,
    nextAction: 'Production',
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-09-02T08:00:00.000Z',
  },
  {
    id: 'PRJ-1036',
    name: 'Mayflower Enclave',
    customerId: 'CUST-07',
    customer: INITIAL_CUSTOMERS[6],
    siteAddress: 'Kondapur, Hyderabad',
    location: 'Kondapur',
    specSummary: '9 Windows (Rehau Soundproof)',
    projectType: 'Residential',
    currentStage: 'design',
    status: 'Designing',
    dealStage: 'New Inquiry',
    dealOwner: { name: 'Chakri S.', avatar: 'CS', color: 'bg-[#0A2E8A]' },
    lastActivity: {
      type: 'clock',
      text: 'Inquired 4h ago',
    },
    estimatedValue: 295000,
    windows: [], // NO WINDOWS YET - Perfect for "Send Quotation (Design First)" workflow!
    quotation: null,
    payments: [],
    productionOrder: null,
    designLocked: false,
    nextAction: 'Send Quotation',
    createdAt: '2026-09-08T08:00:00.000Z',
    updatedAt: '2026-09-08T08:00:00.000Z',
  },
];
